name: CI-followup


# do when CI is completed
on:
  workflow_run:
    workflows:
      - CI
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: echo Goodbye, world!
    - run: |
        echo the workflow "${{ github.event.workflow_run.name }}" triggered me on the commit "${{ github.event.workflow_run.head_commit.id }}".
        echo It was a ${{ github.event.workflow_run.conclusion}}
